select * from usuario;

select * from solicitacao;

SELECT * FROM APARTAMENTO;

-- select para listar todos os chamados
SELECT 
    S.ID_SOLICITACAO,
    S.ID_TIPO_SOLICITACAO,
    S.TITULO_SOLICITACAO,
    S.DESCRICAO_SOLICITACAO,
    S.ID_SOLICITANTE,
    CL.NOME,
    S.ID_ATENDENTE,
    FC.NOME,
    S.DATA_SOLICITACAO,
    S.DATA_EVENTO,
    S.DURACAO_EVENTO,
    S.STATUS,
    S.DATA_ATENDIMENTO
FROM
    SOLICITACAO S
        INNER JOIN
    USUARIO CL ON S.ID_SOLICITANTE = CL.ID_USUARIO
        INNER JOIN
    USUARIO FC ON S.ID_ATENDENTE = FC.ID_USUARIO
        INNER JOIN
    APARTAMENTO AP ON AP.ID_APARTAMENTO = CL.ID_APARTAMENTO
WHERE
    S.ID_SOLICITANTE = 'id_usuario'
        AND CL.ID_TIPO_USUARIO = 3
        OR S.ID_ATENDENTE = 'id_usuario'
        AND FC.ID_TIPO_USUARIO = 2
        OR 1 = 'id_tipo_usuario';
    
-- insercao de solicitações
INSERT INTO SOLICITACAO
	(ID_TIPO_SOLICITACAO,TITULO_SOLICITACAO,DESCRICAO_SOLICITACAO,ID_SOLICITANTE,DATA_EVENTO,DURACAO_EVENTO,STATUS,DATA_ATENDIMENTO)
    VALUES
    ();

-- alteração de solicitacoes

UPDATE SOLICITACAO
SET
	DESCRICAO_SOLICITACAO = '$TESTE',
    DATA_EVENTO = '$DATA_EVENTO',
    DURACAO_EVENTO = '$DURACAO',
    STATUS = 'STATUS',
    DATA_ATENDIMENTO = '$DATA_ATENDIMENTO',
    ID_ATENDENTE = '$ATENDENTE'
WHERE
	ID_SOLICITACAO = '$ID_SOLICITACAO'